default: &DEFAULT
  adapter: mysql
  encoding: utf8
  reconnect: false
  username: trails_forward
  password: trails_forward
  pool: 128
  # host: shinebox

development: &DEVELOPMENT
  <<: *DEFAULT
  database: trails_forward_development

test: &TEST
  <<: *DEFAULT
  adapter: sqlite3
  database: trails_forward_test

cucumber:
  <<: *TEST
